AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for RDS instance

Resources:
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '100'
      BackupRetentionPeriod: 1
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: 8.0.42
      Iops: 1000
      MasterUserPassword: masterusername
      MasterUsername: password