AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Static File Hosting'


Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'william-s3-bucket-yaml'
      WebsiteConfiguration:
        IndexDocument: 'index.hmtl'
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement: 
          - Sid: PublicReadGetObject
            Effect: 'Allow'
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyS3Bucket}/*'


        